from marshmallow import fields

from .base import BasePracticeSchema, EvaluationSchema


class _SustainableEval(EvaluationSchema):
    are_satisfied_with_planting = fields.Boolean(required=True)
    planting_assessment = fields.Boolean(required=True)
    planting_difficulties = fields.Boolean(required=True)
    planting_years = fields.Boolean(required=True)
    planting_importance = fields.Boolean(required=True)
    perform_agricultural_operations = fields.Boolean(required=True)
    has_terraces = fields.Boolean(required=True)
    has_erosion = fields.Boolean(required=True)
    has_soil_disturbance = fields.Boolean(required=True)
    is_soil_compactated = fields.Boolean(required=True)
    soil_preparation_frequency = fields.Boolean(required=True)
    bare_soil_months = fields.Boolean(required=True)
    summer_crops = fields.Boolean(required=True)
    winter_crops = fields.Boolean(required=True)
    animals_on_plating_area = fields.Boolean(required=True)
    has_earthworms = fields.Boolean(required=True)
    are_earthworms_different = fields.Boolean(required=True)
    are_earthworms_good_for_crops = fields.Boolean(required=True)
    earthworms_consequence_for_crops = fields.Boolean(required=True)
    fertilizing_type = fields.Boolean(required=True)
    follow_technical_guidelines = fields.Boolean(required=True)
    uses_manure = fields.Boolean(required=True)
    manure_per_year = fields.Boolean(required=True)
    no_soil_preparation_start = fields.Boolean(required=True)
    no_soil_preparation_end = fields.Boolean(required=True)
    soil_management_start = fields.Boolean(required=True)
    soil_management_end = fields.Boolean(required=True)
    dry_material_accumulation_start = fields.Boolean(required=True)
    dry_material_accumulation_end = fields.Boolean(required=True)
    dry_material_accumulation_tons = fields.Boolean(required=True)


class SustainableSchema(BasePracticeSchema):
    are_satisfied_with_planting = fields.Boolean(required=True)
    planting_assessment = fields.Integer(required=True)
    planting_difficulties = fields.String(missing=None)
    planting_years = fields.Integer(required=True)
    planting_importance = fields.String(missing=None)
    perform_agricultural_operations = fields.Boolean(required=True)
    has_terraces = fields.Boolean(required=True)
    has_erosion = fields.Boolean(required=True)
    has_soil_disturbance = fields.Boolean(required=True)
    is_soil_compactated = fields.Boolean(required=True)
    soil_preparation_frequency = fields.String(missing=None)
    bare_soil_months = fields.Integer(required=True)
    summer_crops = fields.List(fields.String(), missing=None)
    winter_crops = fields.List(fields.String(), missing=None)
    animals_on_plating_area = fields.String(missing=None)
    has_earthworms = fields.Boolean(required=True)
    are_earthworms_different = fields.Integer(missing=None)
    are_earthworms_good_for_crops = fields.Boolean(missing=None)
    earthworms_consequence_for_crops = fields.String(missing=None)
    fertilizing_type = fields.String(required=True)
    follow_technical_guidelines = fields.Boolean(required=True)
    uses_manure = fields.Boolean(required=True)
    manure_per_year = fields.Integer(missing=None)
    no_soil_preparation_start = fields.DateTime(required=True)
    no_soil_preparation_end = fields.DateTime(required=True)
    soil_management_start = fields.DateTime(required=True)
    soil_management_end = fields.DateTime(required=True)
    dry_material_accumulation_start = fields.DateTime(required=True)
    dry_material_accumulation_end = fields.DateTime(required=True)
    dry_material_accumulation_tons = fields.Float(required=True)
    evaluation = fields.Nested(_SustainableEval, missing=None)
