from enum import Enum


class PracticeType(Enum):
    CONTROLLED_TRAFFIC_SYSTEM = 'CONTROLLED_TRAFFIC_SYSTEM'
    CORRECTIVE_QUALITY = 'CORRECTIVE_QUALITY'
    CROP_ROTATION = 'CROP_ROTATION'
    IRRIGATION_USE_EFFICIENCY = 'IRRIGATION_USE_EFFICIENCY'
    PHYTOSANITARY = 'PHYTOSANITARY'
    SOIL_RECHARGE_AND_MOISTURE = 'SOIL_RECHARGE_AND_MOISTURE'
    SOIL_TEMPERATURE = 'SOIL_TEMPERATURE'
    SUSTAINABLE = 'SUSTAINABLE'
    WATER_RUNOFF_CONTAINMENT = 'WATER_RUNOFF_CONTAINMENT'

    @classmethod
    def values(cls):
        return [e.value for e in cls]
